"""
Dagster asset: Gold transformation (dbt-core)

Depends on: silver_service_requests + passing silver_data_quality check
Runs all dbt models in the Gold layer.

Uses dagster-dbt to get full lineage between Dagster assets and dbt models.
Each dbt model becomes a separate Dagster asset automatically.
"""

from __future__ import annotations

from pathlib import Path

from dagster import AssetExecutionContext
from dagster_dbt import DbtCliResource, dbt_assets

PROJECT_ROOT = Path(__file__).parent.parent.parent
DBT_PROJECT_DIR = PROJECT_ROOT / "transform"
DBT_PROFILES_DIR = PROJECT_ROOT / "transform"


# The DbtCliResource is defined once and reused across all dbt assets.
# dagster_dbt wraps dbt-core's CLI; all standard dbt commands work.
dbt_resource = DbtCliResource(
    project_dir=str(DBT_PROJECT_DIR),
    profiles_dir=str(DBT_PROFILES_DIR),
    target="dev",
)


@dbt_assets(
    manifest=DBT_PROJECT_DIR / "target" / "manifest.json",
    dagster_dbt_translator=None,   # Use default translator (model name → asset name)
)
def nyc_311_dbt_assets(
    context: AssetExecutionContext,
    dbt: DbtCliResource,
) -> None:
    """
    Materialize all dbt models in the Gold layer.

    dagster-dbt automatically:
      1. Reads the dbt manifest.json to discover all models
      2. Creates a Dagster asset for each dbt model
      3. Infers dependencies between models from dbt's DAG
      4. Runs `dbt build` (models + tests) and streams logs to Dagster

    The manifest.json is generated by running:
        cd transform && dbt compile
    """
    yield from dbt.cli(["build", "--select", "+tag:gold"], context=context).stream()
